module SmashingBoxer
  class Installer < ExecutionModule
    SmashingBoxer.register_module :installer, self

    action :install,
      proc {install},
      'Creates all nessisary hosts and config files'
    action :uninstall,
      proc {uninstall},
      'Cleans up files generated by the installer'

    def initialize(*args)
      ENV['SMASHING_BOXER_PATH'] = sb_dir
      ENV['ANSIBLE_CONFIG'] = File.join(sb_dir, 'ansible.cfg')
      super
    end

    protected
    def install
      copy_example('site_vars.example.yml', 'site_vars.yml')
      copy_example('hosts.example', 'hosts')
      mkdir 'dev_keys'
      print 'Are you going to user vagrant? (y/n): '
      if gets.chomp == 'y'
        copy_example('Vagrantfile', 'Vagrantfile')
      end
    end

    def uninstall
      rm 'site_vars.yml'
      rm 'hosts'
      rm 'dev_keys'
      rm 'Vagrantfile'
    end

    def rm(file)
      print 'Deleting '.red
      FileUtils.rm_r("#{local_dir}/#{file}")
      puts file
    end

    def mkdir(name)
      print "#{name}: "
      begin
        FileUtils.mkdir(name)
        puts "✔".green
      rescue Exception => e
        puts "✘".green
        raise e
      end
    end

    def copy_example(file, cp_file)
      print "#{cp_file}: "
      begin
        FileUtils.cp("#{sb_dir}/#{file}", "#{local_dir}/#{cp_file}")
        puts "✔".green
      rescue Exception => e
        puts "✘".green
        raise e
      end
    end

    private
    def local_dir
      Dir.pwd
    end
  end
end

class String
  # colorization
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end

  def red
    colorize(31)
  end

  def green
    colorize(32)
  end

  def yellow
    colorize(33)
  end

  def pink
    colorize(35)
  end
end
