Vagrant.configure("2") do |config|

  config.vm.define 'ubuntu1310-i386' do |instance|
    instance.vm.box = 'ubuntu1310-i386'
    #instance.vm.box_url = 'https://dl.dropboxusercontent.com/s/etextqjf5btefbq/ubuntu1310-i386.box'

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "test.yml"
        ansible.sudo_user = 'root'
        ansible.sudo = true
        # ansible.inventory_path = "provisioning/hosts-vagrant"
        # ansible.verbose = 'vvvv'
        # ansible.raw_arguments = ['--user', 'vagrant']
    end
  end
end