- name: Install imagemagick
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev

- name: Register monit memcached config files
  template: src=memcached.j2
            dest=/etc/monit/conf.d/memcached
            mode=u=rw,g=r,o=r
  register: memcached_monit_config

- name: Reload Monit
  command: bash -lc "monit reload"
  when: memcached_monit_config.changed

# zzet.rbenv puts all the rbenv stuff in profile for some reason
# so we gotta use login shells to do this stuff
- name: Install bundler
  shell: bash -lc "gem install bundler"

- name: Rbenv rehash
  shell: bash -lc "rbenv rehash"
